
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

#from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import *
#from tkinter.ttk import *

#Functions for the appication
def delete():
   entry_1.delete("1.0","end")

def submitSQL():
    query = entry_1.get("1.0", "end-1c")
    print(query)

def displayAnnotation():
    newWindow = Toplevel(window)
    # Toplevel widget
    newWindow.title("QEP")
 
    # sets the geometry of toplevel
    newWindow.geometry("600x600")
    Label(newWindow,
          text ="Alternative Query Plan").pack()
    displayTree = Text(newWindow,height = 100,width=100,bg="light cyan")
    displayTree.pack()

    

#The GUI Elements of the database project
window = Tk()
window.title("CZ4031 Database Project 2")
window.geometry("843x891")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 891,
    width = 843,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=("assets/frame0/entry_1.png"))
entry_bg_1 = canvas.create_image(
    426.5,
    292.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=47.0,
    y=165.0,
    width=759.0,
    height=253.0
)

canvas.create_text(
    46.0,
    136.0,
    anchor="nw",
    text="SQL Query",
    fill="#000000",
    font=("DroidSans Regular", 15 * -1)
)

canvas.create_rectangle(
    125.0,
    146.0,
    825.0,
    147.0,
    fill="#9B9B9B",
    outline="")

canvas.create_rectangle(
    26.0,
    145.0,
    39.0,
    146.0,
    fill="#9B9B9B",
    outline="")

canvas.create_rectangle(
    25.999984741210938,
    145.0,
    27.0,
    434.0,
    fill="#9B9B9B",
    outline="")

entry_image_2 = PhotoImage(
    file=("assets/frame0/entry_2.png"))
entry_bg_2 = canvas.create_image(
    425.50001525878906,
    659.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    state= "disabled"
)
entry_2.place(
    x=46.00001525878906,
    y=532.0,
    width=759.0,
    height=253.0
)

canvas.create_text(
    39.0,
    503.0,
    anchor="nw",
    text="Annotations",
    fill="#000000",
    font=("DroidSans Regular", 15 * -1)
)

canvas.create_rectangle(
    124.00001525878906,
    513.0,
    824.0000152587891,
    514.0,
    fill="#9B9B9B",
    outline="")

canvas.create_rectangle(
    25.000015258789062,
    512.0,
    38.00001525878906,
    513.0,
    fill="#9B9B9B",
    outline="")

canvas.create_rectangle(
    25.0,
    512.0,
    26.000015258789062,
    801.0,
    fill="#9B9B9B",
    outline="")

canvas.create_rectangle(
    26.0,
    433.0,
    825.0,
    434.0,
    fill="#9B9B9B",
    outline="")

canvas.create_rectangle(
    24.0,
    801.0,
    823.0,
    802.0,
    fill="#9B9B9B",
    outline="")

canvas.create_rectangle(
    823.0,
    145.0,
    825.0510864257812,
    433.99981689453125,
    fill="#9B9B9B",
    outline="")

canvas.create_rectangle(
    822.0,
    513.0,
    824.0510864257812,
    801.9998168945312,
    fill="#9B9B9B",
    outline="")

button_image_1 = PhotoImage(
    file=("assets/frame0/button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=submitSQL,
    relief="flat"
)
button_1.place(
    x=285.0,
    y=448.0,
    width=283.0,
    height=48.0
)

button_image_2 = PhotoImage(
    file=("assets/frame0/button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=delete,
    relief="flat"
)
button_2.place(
    x=728.0,
    y=119.0,
    width=95.0,
    height=22.454544067382812
)

button_image_3 = PhotoImage(
    file=("assets/frame0/button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command= displayAnnotation,
    relief="flat"
)
button_3.place(
    x=285.0,
    y=816.0,
    width=283.0,
    height=48.0
)

image_image_1 = PhotoImage(
    file=("assets/frame0/image_1.png"))
image_1 = canvas.create_image(
    151.0,
    60.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
